import org.example.move.Movement;
import org.example.entity.Position;
import org.example.gameLogic.Maze;
import org.example.gui.Gui;
import org.example.gui.MovementEvents;
import org.example.interaction.Direction;
import org.junit.jupiter.api.Test;

public class MazeTest {
    @Test
    public void testDisplaySingleWalls(){
        Maze maze = new Maze(20,20,new Position(0,0));
        maze.addWall(new Position(10,10),9,false);
        maze.createNewPlayer(new Position(0,0));
        Movement movement = new Movement();
        String outString = MovementEvents.updateGuiStringOnMovementKeyPressed(movement,maze, Direction.DOWN);
        assert outString.equals("""
                X...................
                P...................
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................
                ..........#########.
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................""");
    }

    @Test
    public void TestComplexWalls(){
        Maze maze = new Maze(20,20,new Position(0,0));
        maze.addWall(new Position(10,10),10,false);
        maze.addWall(new Position(10,0),9,true);
        maze.addWall(new Position(10,3),10,false);
        maze.addWall(new Position(10,8),4,false);
        maze.addWall(new Position(16,8),4,false);
        maze.addWall(new Position(0,5),5,false);
        maze.addWall(new Position(7,5),4,false);
        maze.addWall(new Position(6,11),9,true);
        maze.createNewPlayer(new Position(0,0));
        Movement movement = new Movement();
        String outString = MovementEvents.updateGuiStringOnMovementKeyPressed(movement,maze, Direction.DOWN);
        assert outString.equals("""
                X.........#.........
                P.........#.........
                ..........#.........
                ..........##########
                ..........#.........
                #####..####.........
                ..........#.........
                ..........#.........
                ..........####..####
                ....................
                ..........##########
                ......#.............
                ......#.............
                ......#.............
                ......#.............
                ......#.............
                ......#.............
                ......#.............
                ......#.............
                ......#.............""");
    }
}
